server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://******:3306/slrjy?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: ****

  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    favicon:
      enabled: false
mybatis:
  type-aliases-package: top.slrjy.edu.Entity
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
     top.slrjy.edu : debug
# 打印sql
